// <auto-generated />
using System;
using Farol_Seguro.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farol_Seguro.Migrations
{
    [DbContext(typeof(DbConfig))]
    partial class DbConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Farol_Seguro.Models.Aluno", b =>
                {
                    b.Property<int>("Id_Aluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Aluno"));

                    b.Property<int>("ContadorDenunciasFalsas")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNascimento_Aluno")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genero_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Nivel")
                        .HasColumnType("int");

                    b.Property<bool>("IsBloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_Aluno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Aluno");

                    b.HasIndex("Id_Nivel");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Anexo", b =>
                {
                    b.Property<int>("Id_Anexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Anexo"));

                    b.Property<string>("Caminho_Anexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Denuncia")
                        .HasColumnType("int");

                    b.Property<string>("NomeOriginal_Anexo")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Anexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Anexo");

                    b.HasIndex("Id_Denuncia");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Cargo", b =>
                {
                    b.Property<int>("Id_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Cargo"));

                    b.Property<string>("Nome_Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Cargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Cidade", b =>
                {
                    b.Property<int>("Id_Cidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Cidade"));

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Cidade");

                    b.HasIndex("Id_Estado");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Denuncia", b =>
                {
                    b.Property<int>("Id_Denuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Denuncia"));

                    b.Property<string>("Categoria_Denuncia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao_Denuncia")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DenunciaAnonima")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao_Denuncia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<int>("Id_Escola")
                        .HasColumnType("int");

                    b.Property<bool>("IsFalsa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status_Denuncia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo_Denuncia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Denuncia");

                    b.HasIndex("Id_Aluno");

                    b.HasIndex("Id_Escola");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("Farol_Seguro.Models.DenunciaTestemunha", b =>
                {
                    b.Property<int>("Id_Denuncia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Testemunha")
                        .HasColumnType("int");

                    b.HasKey("Id_Denuncia", "Id_Testemunha");

                    b.HasIndex("Id_Testemunha");

                    b.ToTable("DenunciaTestemunhas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Escola", b =>
                {
                    b.Property<int>("Id_Escola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Escola"));

                    b.Property<string>("Cnpj_Escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco_Escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Cidade")
                        .HasColumnType("int");

                    b.Property<int>("Id_Funcionario")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone_Escola")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Escola");

                    b.HasIndex("Id_Cidade");

                    b.HasIndex("Id_Funcionario");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Estado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Nome_Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla_Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Funcionario", b =>
                {
                    b.Property<int>("Id_Funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Funcionario"));

                    b.Property<string>("Departamento_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Cargo")
                        .HasColumnType("int");

                    b.Property<int>("Id_Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_Funcionario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Funcionario");

                    b.HasIndex("Id_Cargo");

                    b.HasIndex("Id_Nivel");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Farol_Seguro.Models.LogStatus", b =>
                {
                    b.Property<int>("Id_Log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Log"));

                    b.Property<int>("Id_Denuncia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status_Anterior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status_Novo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Log");

                    b.HasIndex("Id_Denuncia");

                    b.HasIndex("Id_Nivel");

                    b.ToTable("LogStatus");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Nivel", b =>
                {
                    b.Property<int>("Id_Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Nivel"));

                    b.Property<string>("Nome_Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Nivel");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Notificacao", b =>
                {
                    b.Property<int>("Id_Notificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Notificacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<int>("Id_Denuncia")
                        .HasColumnType("int");

                    b.Property<bool>("Lida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UrlDestino")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id_Notificacao");

                    b.HasIndex("Id_Aluno");

                    b.HasIndex("Id_Denuncia");

                    b.ToTable("Notificacao");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Resposta", b =>
                {
                    b.Property<int>("Id_Resposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Resposta"));

                    b.Property<DateTime>("Data_Resposta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao_Resposta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Denuncia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Funcionario")
                        .HasColumnType("int");

                    b.HasKey("Id_Resposta");

                    b.HasIndex("Id_Denuncia");

                    b.HasIndex("Id_Funcionario");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Testemunha", b =>
                {
                    b.Property<int>("Id_Testemunha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Testemunha"));

                    b.Property<string>("Nome_Testemunha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone_Testemunha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Testemunha");

                    b.ToTable("Testemunhas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Email_Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha_Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Nivel");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Aluno", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("Id_Nivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Anexo", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Denuncia", "Denuncia")
                        .WithMany("Anexos")
                        .HasForeignKey("Id_Denuncia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Cidade", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Denuncia", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Aluno", "Aluno")
                        .WithMany("Denuncias")
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Farol_Seguro.Models.Escola", "Escola")
                        .WithMany("Denuncias")
                        .HasForeignKey("Id_Escola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Escola");
                });

            modelBuilder.Entity("Farol_Seguro.Models.DenunciaTestemunha", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Denuncia", "Denuncias")
                        .WithMany("DenunciaTestemunhas")
                        .HasForeignKey("Id_Denuncia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farol_Seguro.Models.Testemunha", "Testemunha")
                        .WithMany("DenunciaTestemunhas")
                        .HasForeignKey("Id_Testemunha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncias");

                    b.Navigation("Testemunha");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Escola", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Cidade", "Cidade")
                        .WithMany("Escolas")
                        .HasForeignKey("Id_Cidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farol_Seguro.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Id_Funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Funcionario", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Cargo", "Cargo")
                        .WithMany("Funcionarios")
                        .HasForeignKey("Id_Cargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farol_Seguro.Models.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("Id_Nivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("Farol_Seguro.Models.LogStatus", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Denuncia", "Denuncia")
                        .WithMany()
                        .HasForeignKey("Id_Denuncia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farol_Seguro.Models.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("Id_Nivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Notificacao", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Aluno", "Aluno")
                        .WithMany("Notificacoes")
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farol_Seguro.Models.Denuncia", "Denuncia")
                        .WithMany("Notificacoes")
                        .HasForeignKey("Id_Denuncia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Resposta", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Denuncia", "Denuncia")
                        .WithMany("Respostas")
                        .HasForeignKey("Id_Denuncia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Farol_Seguro.Models.Funcionario", "Funcionario")
                        .WithMany("Respostas")
                        .HasForeignKey("Id_Funcionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Usuario", b =>
                {
                    b.HasOne("Farol_Seguro.Models.Nivel", "Nivel")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_Nivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Aluno", b =>
                {
                    b.Navigation("Denuncias");

                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Cargo", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Cidade", b =>
                {
                    b.Navigation("Escolas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Denuncia", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("DenunciaTestemunhas");

                    b.Navigation("Notificacoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Escola", b =>
                {
                    b.Navigation("Denuncias");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Funcionario", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Nivel", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Farol_Seguro.Models.Testemunha", b =>
                {
                    b.Navigation("DenunciaTestemunhas");
                });
#pragma warning restore 612, 618
        }
    }
}
